### PR TITLE
Added support for multiline helper messages

### LINKED ISSUE #134: Do not Support multi line helper message.
Creating this issue so I can contribute to module by adding mentioned feature.

### PR DESCRIPTION
**Pull request by redbugmilk**
This pull request fixes #134

### CODE REVIEW

**Comment by madoke** [comment]
@redbugmilk try to close and reopen the pull request to trigger the continuous integration build again

**Comment by petrogad** [comment]
Agreed @n4kz can we please get this merged?

**Comment by petrogad** [comment]
Until maintainer returns, I'll be maintaining this at 
https://www.npmjs.com/package/react-native-materialui-textfield

Merged this particular item, thank you @redbugmilk !

**Comment by react-rails** [comment]
@n4kz can you please get this PR merged for new version?

**Comment by n4kz** [comment]
Thanks for PR and sorry for delayed reply. I've released multiline helper support in `0.14.0` with approach different to one proposed here.

**Pull request closed without merging**
