### PR TITLE
"Name" property

### PR DESCRIPTION
**Pull request by isnifer**
Hi!
We've started using this component. I saw example project and I found many performance issues. I think many of them should be fixed with a property called "name". 
This property really helps on the web. I've added this property to the component, it helps here too.

### CODE REVIEW

**Comment by isnifer** [comment]
@n4kz please, take a look :)

**Comment by n4kz** [comment]
Thanks for reporting, could you make clear which performance issues are solved by adding the `name` property?

**Comment by isnifer** [comment]
@n4kz your example contains `onFocus` method. Use for-in loop in that place bad practice for me, I'm sure explicit usage of input `name` property is better.
Next, `onChange` handler is ugly. On every input change you iterate over fields array twice.
Of course, even without input `name` property you can remove [this](https://github.com/n4kz/react-native-material-textfield/pull/22/files#diff-e55bc98107f12615bba2a6649f130228L68) line, but with input `name` property you can remove `forEach` too.

That's why I think input `name` property is cool feature

**Comment by n4kz** [comment]
Example app exists only for demonstration purposes and probably should not be targeted for performance optimisations.

Using string names to reference components is considered an antipattern in recent react versions, please take look at good explanation from Dan Abramov [here](https://news.ycombinator.com/edit?id=12093234). Callback style with curried name argument works well in real app, so I'm quite sure that no change required here.

**Comment by isnifer** [comment]
Hmm...I disagree with you. 
1. There is no string refs
2. `name` attribute it's like the web property on input - what's wrong?
3. If we can write code better - why do not do this?

**Pull request closed without merging**
