### PR TITLE
Render Left Accessory

### PR DESCRIPTION
**Pull request by AlexisLeon**

### CODE REVIEW

**Comment by cosmocoder** [comment]
@n4kz can you please merge this pull request, it is very a useful addition and will help a lot!

**Comment by hirthbrian** [comment]
Any update @n4kz? This would simplify a lot things on my side.

**Comment by petrogad** [comment]
@AlexisLeon would you mind making this PR against a maintained version of this project?

**Comment by lunvjp** [comment]
Hi guys,
* I'm looking for the solution to render left/right Accessory ... like this image.
image
Do you have any ideas with it?
* Currently for now, `renderLeftAccessory` just works when I focus on this Text Input field?
Thanks for having a look.

**Comment by whalemare** [comment]
@n4kz please, we really need this feature.

**Comment by n4kz** [comment]
I've renamed `renderAccessory` to `renderRightAccessory` for consistency and removed animation. In my opinion animation for accessories should be done in child components, so I've passed `active` and `focused` props to render callbacks.

**Comment by aforty** [comment]
Hey thanks for this. Question: is it intended behavior for the label to sit to the right of whatever is rendered in `renderLeftAccessory`? If not would you accept a PR?

Screen Shot 2019-12-13 at 14 34 14

**Pull request merged**
