### PR TITLE
Animated.Text.propTypes.style release build issue

### PR DESCRIPTION
**Pull request by bakoserge**
Replaced Animated.Text.propTypes.style by Text.propTypes.style causing issue on prod release and RN >= .0.62 at least in our case.

### CODE REVIEW

**Comment by bakoserge** [comment]
Screenshot 2020-02-12 at 08 47 22

**Comment by febaisi** [comment]
Good .. We need this too.. @n4kz, can we get this merged?

**Comment by febaisi** [comment]
@n4kz any news?

**Comment by ironhide0396** [comment]
Any update on the above PR ? @n4kz

**Comment by ManasN** [comment]
I'm affected by this too! Temporary forking with this branch. Thank you

**Comment by timvandijck** [comment]
I tried the fix and can confirm it solves the problem and allows you to use the field in a RN 62 app.

**Comment by sajaddp** [comment]
Please check this comment:
https://github.com/n4kz/react-native-material-textfield/issues/238#issuecomment-596026010

**Comment by lumberman** [comment]
This pull can be installed via cli using the next command:

npm install --save n4kz/react-native-material-textfield#729008b847eb38129d0b886e98253d4c11f6d4d3

**Pull request closed without merging**
