### PR TITLE
smooth label animation

### PR DESCRIPTION
**Pull request by mtiziano**
implemented Native Driver on label animation.
translateX translateY and scale with useNativeDriver enabled.
now focus/active label animation is very smooth on both iOS Android

### CODE REVIEW

**Comment by zhibek** [comment]
Nice work @numez! I was just checking ways to use `NativeDriver` in this library and saw you'd already created this PR. @n4kz do you intend to merge this? Anything we can do to increase the chances of this making it into the library?

**Comment by numez** [comment]
Thanks @zhibek! I've removed `-2`, it was a vertical align fix

**Comment by zhibek** [comment]
Looks good @numez.

Looking at the [Travis build](https://travis-ci.org/n4kz/react-native-material-textfield/builds/335126713) for the last commit, most of the snapshots seem to be equivalent (even if they're obviously different, internally).

For example:
```
      <View
        collapsable={undefined}
    +   onLayout={[Function]}
        style={
          Object {
            "position": "absolute",
    -       "top": 36,
    +       "top": 0,
    +       "transform": Array [
    +         Object {
    +           "translateX": 0,
    +         },
    +         Object {
    +           "translateY": 36,
    +         },
    +         Object {
    +           "scale": 1,
    +         },
    +       ],
          }
        }
``` 
Here `"TranslateY": 36` replicates what `"top": 36` did before.

However, there's one place where the snapshot looks like this PR results in a slightly different layout:
```
      <View
        collapsable={undefined}
    +   onLayout={[Function]}
        style={
          Object {
            "position": "absolute",
    -       "top": 16,
    +       "top": 0,
    +       "transform": Array [
    +         Object {
    +           "translateX": 0,
    +         },
    +         Object {
    +           "translateY": 13.600000000000001,
    +         },
    +         Object {
    +           "scale": 0.75,
    +         },
    +       ],
          }
        }
```
I'm trying to work out what the correct `translateY` value should be here...

Once the snapshot differences are proven to not result in any actual layout differences, I think we should run `jest --updateSnapshot` and commit the new snapshots with this PR.

**Comment by FinnGu** [comment]
I would still very much like to see this being merged into the library. I have a 2018 Android flagship and still notice some lag during animations, don't even get me started on performance on lower end devices :(

**Comment by nvojnovic** [comment]
This really helps. Please merge.

**Comment by tiagobnobrega** [comment]
Travis snapshots test are failing as expected from different behaviour. Why is this not merged yet ?

**Comment by n4kz** [comment]
Thanks for PR and sorry for delayed reply. `0.15.0` release contains some animation improvements and even `useNativeDriver` option enabled for label animation and this PR is not actual anymore.

**Pull request closed without merging**
