### PR TITLE
secureTextEntry support added

### PR DESCRIPTION
**Pull request by e1016**
Maybe I should not do PR to the master branch, but from what I see there are no more branches, if necessary let me know. ✌️

### CODE REVIEW

**Comment by e1016** [comment]
I see that "The Travis CI" found problems in my code, but it is an deprecated methods in the life cycle of the component.

**Comment by e1016** [comment]
I see that "The Travis CI" found problems in my code, but it is an deprecated methods in the life cycle of the component. @n4kz

**Comment by n4kz** [comment]
Thanks for PR and sorry for delayed reply. `secureTextEntry` is already supported implicitly and is passed to underlying `TextInput` along with other props. For more details please take a look at example project.

**Comment by tonifirnandes** [comment]
Hi @n4kz , thanks for your great work "this awesome library", but when we add secureTextEntry={true}, the text input still not being masked with dot properly.

Envi:
- rn 0.59.1
- rn-material-textfield latest

**Review by tonifirnandes — COMMENTED** [review]
.

**Pull request closed without merging**
