### PR TITLE
Handling null input on a value

### PR DESCRIPTION
**Pull request by petrogad**
We have a few spots where we're passing data directly from reducers that could have a null value.  While it appears for the most part the field handles this, on line 370, it was doing a .length check prior to seeing if something was there.

Lets default to a string if undefined to resolve this potential bug.

### CODE REVIEW

**Comment by petrogad** [comment]
Closes #115

**Comment by petrogad** [comment]
Is there something I need to do to execute a new build? I ran tests locally and saw them working - Happy to make adjustments just let me know.

**Comment by petrogad** [comment]
Thanks @n4kz for the wonderful package! Hoping to have this merged to avoid our proxy of the method.

Cheers

**Comment by n4kz** [comment]
Thanks for PR and sorry fore delayed reply. I've fixed crash on null value in 44930675.

**Pull request closed without merging**
